server:
  bind_endpoint: 127.0.0.1:30921

private_key:
  hex: 7c5c8d3114ac2410249ca2baae7dec86ac2950a389ac44a5fdca8941b92b6c86

tokens:
  expiration_seconds: 3024000

metrics:
  bind_endpoint: 127.0.0.1:39022

payments:
  nilchain_url: http://rpc.testnet-numia.nilchain-rpc-proxy.nilogy.xyz/
