server:
  bind_endpoint: 127.0.0.1:30921

private_key:
  hex: 7c5c8d3114ac2410249ca2baae7dec86ac2950a389ac44a5fdca8941b92b6c86

tokens:
  expiration_seconds: 3024000

metrics:
  bind_endpoint: 127.0.0.1:39022

payments:
  nilchain_url: http://127.0.0.1:48102

  subscriptions:
    renewal_threshold_seconds: 60 
    length_seconds: 120

postgres:
  url: postgres://postgres:admin@127.0.0.1:5432/postgres
