services:
  db:
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  nilchain:
    image: ghcr.io/nillionnetwork/nilchain-devnet:main
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "26648:26648" # json rpc
      - "26649:26649" # grpc
      - "26650:26650" # rest

  token-price-api:
    image: caddy:2
    ports:
      - "30923:80"
    command: |
      caddy respond --listen :80 --body '{"nillion":{"usd":1}}' --header "Content-Type: application/json" 
