services:
  db:
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  nilchain:
    image: ghcr.io/nillionnetwork/nilchain-devnet:v0.1.0
    restart: unless-stopped
    shm_size: 128mb

