services:
  db:
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  nilchain:
    image: ghcr.io/nillionnetwork/nilchaind:v0.2.5
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./nilchaind:/opt/nilchaind-configs
    entrypoint: ["/bin/sh", "-c", "cp -r /opt/nilchaind-configs /opt/nilchaind && nilchaind start --home /opt/nilchaind"]
    ports:
      - 26648:26648 # JSON RPC
      - 26649:26649 # gRPC
      - 26650:26650 # REST




