on:
  pull_request:
  push:
    branches:
      - main

name: Merge checks

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: clippy, rustfmt

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check 

      - name: Cargo test
        run: cargo test

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

